server {
    listen 8081;
    server_name _;

    root /var/www/phpmyadmin;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 60;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    client_max_body_size 512m;

    error_log  /var/log/nginx/phpmyadmin-error.log warn;
    access_log /var/log/nginx/phpmyadmin-access.log;
}
