apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: techdomov
  labels:
    app.kubernetes.io/name: techdomov
    app.kubernetes.io/component: app
type: Opaque
data:
  # ── Laravel ──────────────────────────────────────────────
  # Value je: base64:rRhWlB9yt4se6jvO3zRe0k2LfUNY4zBc7dOV5Mg1tlw=
  APP_KEY: "YmFzZTY0OnJSaFdsQjl5dDRzZTZqdk8zelJlMGsyTGZVTlk0ekJjN2RPVjVNZzF0bHc9"

  # ── Database ─────────────────────────────────────────────
  DB_PASSWORD: "WmVsaW9fNjIzNg=="
  DB_ROOT_PASSWORD: "WmVsaW9fNjIzNg=="

  # ── Mail ─────────────────────────────────────────────────
  MAIL_PASSWORD: "WmVsaW9fNjIzNg=="

  # ── PayPal ───────────────────────────────────────────────
  PAYPAL_SANDBOX_CLIENT_ID: "QWVrZGUxUUJ5VVZzY1ZQclFBd0J3dXNjUTd2Ujhkd0huZUJfS1RkLXp1aGRmclhic0c3OHdYRXBzbmVzcHVXRDB1T3QxOWdWdDA3VVpYWFQ="
  PAYPAL_SANDBOX_CLIENT_SECRET: "RVBzUGVYMGJpeVM2WWh5bTJFWEhQYXc1dWtvaDVvTW1LY0IyRHNSN0dUX2RMV3ZiSV9WS2pRaGFlLW1ydDJKM0pXYkxITXl6N0t3XzRPUzQ="
  PAYPAL_LIVE_CLIENT_ID: "QVZoSkxnVnNoVlVRbjZKRFRFUmZEMTdlQTVaYkdZX0pZN2ZVTkw4WEh0aXd0YkpLRG1WSE9IckVDN2phUUxIby1YM1c4Mmpld0VMWE1TQlo="
  PAYPAL_LIVE_CLIENT_SECRET: "RUdieVBqQjY4SlBfc0ViWWEtZzR6RW1BQ1p4VXBYdFk4UHVJZ0dzekxyQ2FQWTAwbW8xU1lSU1ZGY05qNkpQUE5qNWpvZlA1cVgxX09QQ1Q="
  PAYPAL_LIVE_APP_ID: ""
  PAYPAL_WEBHOOK_ID: "N0g0MDg2NzFDMDYyMjAzNE0="

  # ── Google Ads ───────────────────────────────────────────
  GOOGLE_ADS_CUSTOMER_ID: "NDg0LTM4My0wMjI3"
  GOOGLE_ADS_DEVELOPER_TOKEN: "QVJPRnBFRTV2bndHSWl3Si04aE84Zw=="
  GOOGLE_ADS_CLIENT_ID: "REDACTED_CLIENT_ID"
  GOOGLE_ADS_CLIENT_SECRET: "REDACTED_CLIENT_SECRET"
  GOOGLE_ADS_REFRESH_TOKEN: "MS8vMDNWbERjb3dIQ1MzM0NnWUlBUkFBR0FNU05nRi1MOUlyRl9IVmZuZEJhdE5fZWpGYUpNNFh1YnFrSURyT3l2SkRVR3lIN0tZY01qVmp4MEdzdFZ3NUIwQ011cUpnRU40V2t3"
