apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage
  namespace: techdomov
  labels:
    app.kubernetes.io/name: techdomov
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard-rwo"
  resources:
    requests:
      storage: 5Gi
